version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookstore-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongP@ssw0rd!
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MyStrongP@ssw0rd!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: bookstore-backend
    container_name: bookstore-backend
    ports:
      - "8080:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookStore;User=sa;Password=MyStrongP@ssw0rd!;TrustServerCertificate=True
      - Jwt__Key=qwertyuiopasdfghjklzxcvbnm@#$qwertyuiopasdfghjklzxcvbnm
      - Jwt__Issuer=PustakParadise
      - Jwt__Audience=audience
      - EmailSettings__Host=smtp.gmail.com
      - EmailSettings__Port=587
      - EmailSettings__Name=Pustak Paradise
      - EmailSettings__EmailId=nalawadeshirish5465@gmail.com
      - EmailSettings__UserName=ssn
      - EmailSettings__Password=ewlu mtqu zirg cunj
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  sql_data:
